version: '3.8'

services:
  app:
    build: .
    image: wsd_ecom_app:latest
    ports:
      - "8080:8080"
    depends_on:
      - flyway
      - mysql

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql:3306/wsd_ecom_db -user=root -password=root -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wsd_ecom_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
